// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPrsIJsXPzdLmmypWenzl-VGIwd0X6ss',
    appId: '1:821679543275:web:ef02c48ff64da41699ffae',
    messagingSenderId: '821679543275',
    projectId: 'mad-hw4-be6ce',
    authDomain: 'mad-hw4-be6ce.firebaseapp.com',
    storageBucket: 'mad-hw4-be6ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZDE3zc3TRkn0H03okGdvOmtAEP_goUk',
    appId: '1:821679543275:android:d3cbaef04371dcf099ffae',
    messagingSenderId: '821679543275',
    projectId: 'mad-hw4-be6ce',
    storageBucket: 'mad-hw4-be6ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_c6pU9nPnMBZ__ou2KqHI5GQLdUxCbTU',
    appId: '1:821679543275:ios:e1fed8b2e357d83099ffae',
    messagingSenderId: '821679543275',
    projectId: 'mad-hw4-be6ce',
    storageBucket: 'mad-hw4-be6ce.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_c6pU9nPnMBZ__ou2KqHI5GQLdUxCbTU',
    appId: '1:821679543275:ios:e1fed8b2e357d83099ffae',
    messagingSenderId: '821679543275',
    projectId: 'mad-hw4-be6ce',
    storageBucket: 'mad-hw4-be6ce.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPrsIJsXPzdLmmypWenzl-VGIwd0X6ss',
    appId: '1:821679543275:web:cc4729f3be1e3f2499ffae',
    messagingSenderId: '821679543275',
    projectId: 'mad-hw4-be6ce',
    authDomain: 'mad-hw4-be6ce.firebaseapp.com',
    storageBucket: 'mad-hw4-be6ce.firebasestorage.app',
  );
}
